# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ruby-ntlm}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["MATSUYAMA Kengo"]
  s.date = %q{2010-09-16}
  s.description = %q{NTLM implementation for Ruby. It's early alpha version.}
  s.email = %q{macksx@gmail.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "examples/http.rb",
     "examples/http2.rb",
     "examples/imap.rb",
     "examples/mechanize.rb",
     "examples/smtp.rb",
     "lib/ntlm.rb",
     "lib/ntlm/http.rb",
     "lib/ntlm/imap.rb",
     "lib/ntlm/mechanize.rb",
     "lib/ntlm/message.rb",
     "lib/ntlm/smtp.rb",
     "lib/ntlm/util.rb",
     "ruby-ntlm.gemspec",
     "test/auth_test.rb",
     "test/function_test.rb",
     "test/test_helper.rb",
     "unused/extconf.rb",
     "unused/http_example.rb",
     "unused/ntlm.c"
  ]
  s.homepage = %q{http://github.com/macks/}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{NTLM implementation for Ruby}
  s.test_files = [
    "test/auth_test.rb",
     "test/function_test.rb",
     "test/test_helper.rb",
     "examples/http.rb",
     "examples/http2.rb",
     "examples/imap.rb",
     "examples/mechanize.rb",
     "examples/smtp.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

